version: '3'

tasks:
  # Development
  dev:
    desc: Build frontend, build backend, and run the server
    cmds:
      - task: frontend:build
      - task: backend:build
      - task: backend:run

  # Frontend tasks
  frontend:build:
    desc: Build the frontend React application
    dir: frontend
    cmds:
      - npm run build
    sources:
      - src/**/*
      - index.html
      - package.json
      - vite.config.ts
      - tsconfig.json
    generates:
      - ../assets/**/*

  # Backend tasks
  backend:build:
    desc: Build the Rust backend
    cmds:
      - cargo build
    sources:
      - src/**/*.rs
      - Cargo.toml
      - Cargo.lock
    generates:
      - target/debug/secan

  backend:run:
    desc: Run the backend server
    cmds:
      - cargo run

  # Cleanup
  clean:
    desc: Clean all build artifacts
    cmds:
      - rm -rf frontend/node_modules
      - rm -rf frontend/dist
      - rm -rf target
      - rm -rf assets

  # Testing
  test:
    desc: Run all tests
    cmds:
      - task: test:backend
      - task: test:frontend

  test:backend:
    desc: Run backend tests
    cmds:
      - cargo test

  test:frontend:
    desc: Run frontend tests
    dir: frontend
    cmds:
      - npm test

  # Linting
  lint:
    desc: Run all linters
    cmds:
      - task: lint:backend
      - task: lint:frontend

  lint:backend:
    desc: Run Rust linter
    cmds:
      - cargo clippy
      - cargo fmt --check

  lint:frontend:
    desc: Run TypeScript/React linter
    dir: frontend
    cmds:
      - npm run lint

  # Formatting
  format:
    desc: Format all code
    cmds:
      - cargo fmt --all
      - task: format:frontend

  format:frontend:
    desc: Format frontend code
    dir: frontend
    cmds:
      - npx prettier --write src/

  # Test data
  data:bootstrap:
    desc: Bootstrap test data in Elasticsearch
    cmds:
      - ./scripts/bootstrap-test-data.sh

  data:cleanup:
    desc: Clean up test data from Elasticsearch
    cmds:
      - ./scripts/cleanup-test-data.sh

  # Docker Elasticsearch
  docker:up:
    desc: Start Elasticsearch with Docker Compose
    cmds:
      - docker-compose up -d

  docker:down:
    desc: Stop Elasticsearch
    cmds:
      - docker-compose down

  docker:build-amd64:
    desc: Build Docker image for amd64
    cmds:
      - docker build --platform linux/amd64 -t secan:latest .

  docker:build-multiarch:
    desc: Build Docker image for multiple architectures
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 -t secan:latest .

  # Full development setup
  full-dev:
    desc: Start Elasticsearch, bootstrap data, and run dev server
    cmds:
      - task: docker:up
      - sleep 5
      - task: data:bootstrap
      - task: dev

  # Release builds
  release:frontend:
    desc: Build frontend for release
    dir: frontend
    cmds:
      - npm ci
      - npm run build

  release:backend:
    desc: Build backend for release
    cmds:
      - cargo build --release

  release:backend-target:
    desc: Build backend for specific target
    cmds:
      - cargo build --release --target $TARGET

  # Cross-compilation
  cross:install:
    desc: Install cross-compilation tool
    cmds:
      - cargo install cross --git https://github.com/cross-rs/cross

  cross:build:
    desc: Build backend using cross for specific target
    cmds:
      - cross build --release --target $TARGET

  # Packaging
  pkg:binary:
    desc: Package binary as tarball (set TARGET and NAME env vars)
    cmds:
      - mkdir -p artifacts
      - cd target/$TARGET/release && tar czf ../../artifacts/secan-$NAME.tar.gz secan && sha256sum secan-$NAME.tar.gz > ../../artifacts/secan-$NAME.tar.gz.sha256

  # Version management
  version:bump:
    desc: Bump version and create git tag. Usage - task version:bump TAG=v0.2.0
    cmds:
      - ./scripts/bump-version.sh {{.TAG}}

  # Documentation tasks
  docs:dev:
    desc: Start documentation development server
    dir: docs
    cmds:
      - npm run dev

  docs:build:
    desc: Build documentation for production
    dir: docs
    cmds:
      - npm ci
      - npm run build
    sources:
      - src/**/*
      - astro.config.mjs
      - package.json
      - package-lock.json
    generates:
      - dist/**/*

  docs:preview:
    desc: Preview production documentation build
    dir: docs
    cmds:
      - npm run preview

  docs:rust-api:
    desc: Generate Rust API documentation
    cmds:
      - cargo doc --no-deps --release
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - target/doc/**/*

  docs:integrate-api:
    desc: Integrate Rust API docs into Starlight output
    cmds:
      - mkdir -p docs/dist/api
      - cp -r target/doc/secan/* docs/dist/api/
    sources:
      - target/doc/secan/**/*

  docs:build-complete:
    desc: Build complete documentation site (Starlight + Rust API)
    cmds:
      - task: docs:rust-api
      - task: docs:build
      - task: docs:integrate-api
    sources:
      - src/**/*.rs
      - Cargo.toml
      - docs/src/**/*
      - docs/astro.config.mjs
      - docs/package.json
    generates:
      - docs/dist/**/*
