/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version endpoint
         * @description Returns the current version and git information
         *     This endpoint does not require authentication
         */
        get: operations["get_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login endpoint for local users
         * @description Authenticates a user with username and password
         *
         *     # Requirements
         *
         *     Validates: Requirements 29.2, 30.4
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout endpoint
         * @description Invalidates the user's session and clears the session cookie
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user info
         * @description Returns authenticated user information or 401 if not authenticated
         */
        get: operations["get_current_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Handle OIDC callback
         * @description Exchanges the authorization code for tokens and creates a session
         *
         *     # Requirements
         *
         *     Validates: Requirements 29.2, 30.4
         */
        get: operations["oidc_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Initiate OIDC authentication flow
         * @description Redirects the user to the OIDC provider's authorization endpoint
         *
         *     # Requirements
         *
         *     Validates: Requirements 29.2
         */
        get: operations["oidc_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authentication status */
        get: operations["get_auth_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_clusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/indices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_indices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/indices/{index_name}/shards/{shard_num}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get shards information using SDK typed methods
         * @description Returns shards info in frontend-compatible format
         *
         *     # Requirements
         *
         *     Validates: Requirements 4.8
         */
        get: operations["get_shard_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_nodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/nodes/{node_id}/shards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get shards allocated on a specific node
         * @description Returns shard information for shards on the specified node only.
         *     This is more efficient than fetching all shards and filtering client-side.
         *
         *     # Requirements
         *
         *     Validates: Requirements 4.8
         */
        get: operations["get_node_shards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/nodes/{node_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get detailed stats for a specific node
         * @description Returns comprehensive node statistics including thread pools, shards, and metrics
         *
         *     # Requirements
         *
         *     Validates: Requirements 14.3, 14.4, 14.5
         */
        get: operations["get_node_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/proxy/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proxy request to Elasticsearch cluster
         * @description Forwards the request to the specified cluster and returns the response
         *
         *     # Requirements
         *
         *     Validates: Requirements 2.16, 29.3
         */
        get: operations["proxy_request"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/relocate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Relocate a shard from one node to another
         * @description Executes the Elasticsearch cluster reroute API to move a shard
         *
         *     # Requirements
         *
         *     Validates: Requirements 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 6.10, 6.11, 8.1, 8.2, 8.3, 8.4
         */
        post: operations["relocate_shard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cluster settings
         * @description Returns cluster settings in JSON format
         *     Optionally includes default settings with `include_defaults` query parameter
         */
        get: operations["get_cluster_settings"];
        /**
         * Update cluster settings
         * @description Updates persistent and/or transient cluster settings
         *     Only modified settings need to be provided in the request body
         */
        put: operations["update_cluster_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/shards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_shards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cluster statistics using SDK typed methods
         * @description Returns cluster stats in frontend-compatible format
         *
         *     # Requirements
         *
         *     Validates: Requirements 4.1, 4.2, 4.3
         */
        get: operations["get_cluster_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all active tasks in a cluster
         * @description # Requirements
         *
         *     Validates: Requirement 1, 2, 3 (Task display with filtering)
         */
        get: operations["fetch_cluster_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get detailed information about a specific task
         * @description # Requirements
         *
         *     Validates: Requirement 4 (Task details modal)
         */
        get: operations["get_task_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a specific task
         * @description # Requirements
         *
         *     Validates: Requirement 5 (Cancel task action)
         */
        post: operations["cancel_cluster_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/topology/sankey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sankey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{cluster_id}/topology/tiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /topology/tiles
         *     Currently uses a minimal server-side generator that computes positions by
         *     ported layout and intersects nodes with tile bounding boxes. This is the
         *     first step toward a full tile generator backed by ClusterManager.
         */
        post: operations["post_tiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check endpoint
         * @description Returns HTTP 200 if the server is healthy
         *     This endpoint does not require authentication
         *
         *     # Requirements
         *
         *     Validates: Requirements 39.1, 39.2, 39.5
         */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/validate-prometheus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Prometheus endpoint connectivity
         * @description Tests connection to a Prometheus endpoint and validates it can be reached.
         *     Used to verify configuration before saving.
         *
         *     # Requirements
         *
         *     Validates: Requirements 2.0, 2.1
         */
        post: operations["validate_prometheus_endpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cluster metrics
         * @description Returns metrics for a specific cluster.
         *     Currently uses internal Elasticsearch metrics.
         *     Future: Will support Prometheus metrics based on cluster configuration.
         *
         *     # Query Parameters
         *     - `start` - Unix timestamp (seconds) for range start. Defaults to 24 hours ago.
         *     - `end` - Unix timestamp (seconds) for range end. Defaults to current time.
         *
         *     # Requirements
         *
         *     Validates: Requirements 1.0, 1.1
         */
        get: operations["get_cluster_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{cluster_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cluster metrics history (for heatmap visualization)
         * @description Returns cluster health status snapshots over a time period for heatmap visualization.
         *     Currently returns placeholder data. Will be populated with Prometheus historical data.
         *
         *     # Query Parameters
         *     - `start` - Unix timestamp (seconds) for range start. Defaults to 7 days ago.
         *     - `end` - Unix timestamp (seconds) for range end. Defaults to current time.
         *
         *     # Requirements
         *
         *     Validates: Requirements 3.0
         */
        get: operations["get_cluster_metrics_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/{cluster_id}/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get node metrics from Prometheus
         * @description Returns time series metrics for a specific node when cluster uses Prometheus metrics source.
         *
         *     # Query Parameters
         *     - `start` - Unix timestamp (seconds) for range start. Defaults to 24 hours ago.
         *     - `end` - Unix timestamp (seconds) for range end. Defaults to current time.
         *
         *     # Requirements
         *
         *     Validates: Requirements 1.0, 1.1
         */
        get: operations["get_node_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check endpoint
         * @description Returns HTTP 200 if the server is ready to accept requests
         *     This endpoint does not require authentication
         *
         *     # Requirements
         *
         *     Validates: Requirements 39.3, 39.6
         */
        get: operations["readiness_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Auth status response */
        AuthStatusResponse: {
            /** @example open */
            mode: string;
            /** @example false */
            oidc_enabled: boolean;
            /** Format: int64 */
            oidc_redirect_delay?: number | null;
        };
        /** @description Response from cancel task endpoint */
        CancelTaskResponse: {
            /** @example Task cancelled successfully */
            message: string;
            /** @example true */
            success: boolean;
        };
        /** @description Individual cluster health detail */
        ClusterDetail: {
            error?: string | null;
            /** @example prod-1 */
            id: string;
            /** @example Production */
            name?: string | null;
            /** @example green */
            status: string;
        };
        /** @description Error response for cluster operations */
        ClusterErrorResponse: {
            accessible_reason?: string | null;
            error: string;
            message: string;
        };
        /** @description Health status of configured clusters */
        ClusterHealthStatus: {
            /** @description Details per cluster */
            details: components["schemas"]["ClusterDetail"][];
            /**
             * @description Number of clusters that are healthy
             * @example 1
             */
            healthy: number;
            /**
             * @description Total number of configured clusters
             * @example 2
             */
            total: number;
            /**
             * @description Number of clusters that are unhealthy
             * @example 1
             */
            unhealthy: number;
        };
        /** @description Cluster information for API responses */
        ClusterInfo: {
            accessible: boolean;
            accessible_reason?: string | null;
            id: string;
            /** @description Metrics source (internal or prometheus) */
            metrics_source: components["schemas"]["MetricsSource"];
            name?: string | null;
            nodes: string[];
        };
        /** @description Cluster metrics history response */
        ClusterMetricsHistoryResponse: {
            /** @example prod-1 */
            cluster_id: string;
            data: components["schemas"]["ClusterMetricsPoint"][];
            /** @description Prometheus queries used for each metric (metric_name -> full query) */
            prometheus_queries?: {
                [key: string]: string;
            } | null;
            raw_metrics?: null | components["schemas"]["RawMetrics"];
            time_range: components["schemas"]["TimeRange"];
        };
        /** @description Cluster metrics data point for frontend consumption */
        ClusterMetricsPoint: {
            /** Format: double */
            cpu_percent?: number | null;
            /** @example 2024-01-01T00:00:00Z */
            date: string;
            /** Format: int64 */
            disk_total_bytes?: number | null;
            /** Format: int64 */
            disk_used_bytes?: number | null;
            /** Format: int64 */
            document_count?: number | null;
            /** @example green */
            health: string;
            /** Format: int32 */
            index_count?: number | null;
            /** Format: int64 */
            memory_non_heap_bytes?: number | null;
            /** Format: int64 */
            memory_used_bytes?: number | null;
            /**
             * Format: int32
             * @example 5
             */
            node_count: number;
            /** Format: int32 */
            shard_count?: number | null;
            /**
             * Format: int64
             * @example 1704067200
             */
            timestamp: number;
            /** Format: int32 */
            unassigned_shards?: number | null;
        };
        /** @description Request body for updating cluster settings */
        ClusterSettingsUpdateRequest: {
            /** @description Persistent settings (survive cluster restarts) */
            persistent?: unknown;
            /** @description Transient settings (do not survive cluster restarts) */
            transient?: unknown;
        };
        /** @description Cluster stats response for frontend */
        ClusterStatsResponse: {
            /** Format: int32 */
            activePrimaryShards: number;
            /** Format: int32 */
            activeShards: number;
            clusterName: string;
            /** Format: int32 */
            cpuPercent?: number | null;
            /** Format: int64 */
            diskTotal?: number | null;
            /** Format: int64 */
            diskUsed?: number | null;
            esVersion?: string | null;
            /** @example green */
            health: string;
            /** Format: int32 */
            initializingShards: number;
            /** Format: double */
            loadAverage15m?: number | null;
            /** Format: double */
            loadAverage1m?: number | null;
            /** Format: double */
            loadAverage5m?: number | null;
            /** Format: int64 */
            memoryTotal?: number | null;
            /** Format: int64 */
            memoryUsed?: number | null;
            /** Format: int32 */
            numberOfDataNodes: number;
            /** Format: int64 */
            numberOfDocuments: number;
            /** Format: int32 */
            numberOfIndices: number;
            /** Format: int32 */
            numberOfNodes: number;
            /** Format: int32 */
            relocatingShards: number;
            /** Format: int32 */
            unassignedShards: number;
        };
        /**
         * @description List all configured clusters
         *
         *     Returns a list of all clusters with filtering and pagination
         *
         *     # Requirements
         *
         *     Validates: Requirements 2.15
         */
        ClustersQueryParams: {
            /** @example green,yellow */
            health?: string;
            /**
             * Format: int32
             * @default 1
             * @example 1
             */
            page: number;
            /**
             * Format: int32
             * @default 50
             * @example 50
             */
            page_size: number;
            /** @example production */
            search?: string;
            /** @example 8.0.0 */
            version?: string;
        };
        /** @description Status of a single component */
        ComponentStatus: {
            message?: string | null;
            /** @example healthy */
            status: string;
        };
        /** @description Status of external dependencies */
        DependenciesStatus: {
            /** @description Status of Elasticsearch/OpenSearch clusters */
            clusters: components["schemas"]["ClusterHealthStatus"];
            /** @description Status of session manager */
            session_manager: components["schemas"]["ComponentStatus"];
        };
        /** @description Error response */
        ErrorResponse: {
            error: string;
            message: string;
        };
        /** @description Filesystem statistics */
        FileSystemStats: {
            /** Format: int64 */
            available: number;
            path: string;
            /** Format: int64 */
            total: number;
            type: string;
            /** Format: int64 */
            used: number;
        };
        /** @description GC collector statistics */
        GcCollectorStats: {
            /** Format: int64 */
            collectionCount: number;
            /** Format: int64 */
            collectionTimeInMillis: number;
        };
        /** @description Health check response */
        HealthResponse: {
            /** @example Server is running */
            message: string;
            /** @example healthy */
            status: string;
        };
        /** @description Index info response for frontend */
        IndexInfoResponse: {
            /** Format: int64 */
            docsCount: number;
            health: string;
            name: string;
            /** Format: int32 */
            primaryShards: number;
            /** Format: int32 */
            replicaShards: number;
            status: string;
            /** Format: int64 */
            storeSize: number;
            uuid?: string | null;
        };
        /** @description Indexing statistics */
        IndexingStats: {
            /** Format: int64 */
            deleteTimeInMillis: number;
            /** Format: int64 */
            deleteTotal: number;
            /** Format: int32 */
            indexCurrent: number;
            /** Format: int64 */
            indexFailed: number;
            /** Format: int64 */
            indexTimeInMillis: number;
            /** Format: int64 */
            indexTotal: number;
        };
        /**
         * @description Get indices information using SDK typed methods with pagination
         *
         *     Returns paginated indices info in frontend-compatible format
         *
         *     # Requirements
         *
         *     Validates: Requirements 4.7
         */
        IndicesQueryParams: {
            /** @default false */
            affected: boolean;
            /** @example green,yellow */
            health?: string;
            /**
             * Format: int32
             * @default 1
             * @example 1
             */
            page: number;
            /**
             * Format: int32
             * @default 50
             * @example 50
             */
            page_size: number;
            /** @example logs- */
            search?: string;
            /** @default false */
            show_special: boolean;
            /** @example open,close */
            status?: string;
        };
        /** @description JVM statistics */
        JvmStats: {
            gcCollectors: {
                [key: string]: components["schemas"]["GcCollectorStats"];
            };
        };
        /** @description Metric point with optional labels for multi-series support */
        LabeledMetricPoint: {
            /** @description Labels in logfmt format (e.g., {"area": "heap", "node": "node-1"}) */
            labels?: {
                [key: string]: string;
            } | null;
            /**
             * Format: int64
             * @example 1704067200
             */
            timestamp: number;
            /**
             * Format: double
             * @example 75.5
             */
            value: number;
        };
        /** @description Login request for local users */
        LoginRequest: {
            /** @example password123 */
            password: string;
            /** @example admin */
            username: string;
        };
        /** @description Login response */
        LoginResponse: {
            message: string;
            success: boolean;
        };
        /** @description Query parameters for metrics requests */
        MetricsQuery: {
            /**
             * Format: int64
             * @description End timestamp (Unix seconds). If not provided, defaults to now
             */
            end?: number | null;
            /**
             * Format: int64
             * @description Start timestamp (Unix seconds). If not provided, defaults to 24 hours ago
             */
            start?: number | null;
        };
        /**
         * @description Metrics data source for cluster
         * @enum {string}
         */
        MetricsSource: "internal" | "prometheus";
        /** @description Network statistics */
        NetworkStats: {
            /** Format: int64 */
            rxBytes: number;
            /** Format: int64 */
            txBytes: number;
        };
        /** @description Node detail stats response for frontend */
        NodeDetailStatsResponse: {
            /** Format: int32 */
            cpuPercent: number;
            /** Format: int32 */
            diskPercent: number;
            /** Format: int64 */
            diskTotal: number;
            /** Format: int64 */
            diskUsed: number;
            fs?: null | components["schemas"]["FileSystemStats"];
            /** Format: int64 */
            heapMax: number;
            /** Format: int32 */
            heapPercent: number;
            /** Format: int64 */
            heapUsed: number;
            id: string;
            indexing?: null | components["schemas"]["IndexingStats"];
            ip?: string | null;
            isMaster: boolean;
            isMasterEligible: boolean;
            jvm?: null | components["schemas"]["JvmStats"];
            jvmVersion?: string | null;
            loadAverage?: number[] | null;
            name: string;
            network?: null | components["schemas"]["NetworkStats"];
            roles: string[];
            search?: null | components["schemas"]["SearchStats"];
            shards?: null | components["schemas"]["ShardStats"];
            threadPools?: {
                [key: string]: components["schemas"]["ThreadPoolStats"];
            } | null;
            uptime: string;
            /** Format: int64 */
            uptimeMillis: number;
            version?: string | null;
        };
        /** @description Node info response for frontend */
        NodeInfoResponse: {
            /** Format: int32 */
            cpuPercent?: number | null;
            /** Format: int64 */
            diskTotal: number;
            /** Format: int64 */
            diskUsed: number;
            /** Format: int64 */
            heapMax: number;
            /** Format: int32 */
            heapPercent: number;
            /** Format: int64 */
            heapUsed: number;
            /** @example node-1 */
            id: string;
            ip?: string | null;
            isMaster: boolean;
            isMasterEligible: boolean;
            loadAverage?: number[] | null;
            name: string;
            roles: string[];
            tags?: string[] | null;
            uptime?: string | null;
            /** Format: int64 */
            uptimeMillis?: number | null;
            version?: string | null;
        };
        /** @description Node metrics history response */
        NodeMetricsHistoryResponse: {
            /** @example prod-1 */
            cluster_id: string;
            data: components["schemas"]["NodeMetricsPoint"][];
            /** @example node-1 */
            node_id: string;
            /** @description Prometheus queries used for each metric (metric_name -> full query) */
            prometheus_queries?: {
                [key: string]: unknown;
            } | null;
            time_range: components["schemas"]["TimeRange"];
        };
        /** @description Node metrics data point for frontend consumption */
        NodeMetricsPoint: {
            /** Format: double */
            cpu_percent?: number | null;
            /** @example 2024-01-01T00:00:00Z */
            date: string;
            /** Format: double */
            disk_used_percent?: number | null;
            /** Format: int64 */
            heap_max_bytes?: number | null;
            /** Format: int64 */
            heap_used_bytes?: number | null;
            /** Format: double - Heap usage as a percentage (0-100), calculated as (heap_used_bytes / heap_max_bytes) * 100 */
            heap_used_percent?: number | null;
            /** Format: double */
            load_average_15m?: number | null;
            /** Format: double */
            load_average_1m?: number | null;
            /** Format: double */
            load_average_5m?: number | null;
            /**
             * Format: int64
             * @example 1704067200
             */
            timestamp: number;
        };
        /**
         * @description Get nodes information using SDK typed methods with pagination
         *
         *     Returns paginated nodes info in frontend-compatible format
         *
         *     # Requirements
         *
         *     Validates: Requirements 4.6, 14.1, 14.2
         */
        NodesQueryParams: {
            /** @example node-1,node-2 */
            nodes?: string | null;
            /**
             * Format: int32
             * @default 1
             * @example 1
             */
            page: number;
            /**
             * Format: int32
             * @default 50
             * @example 50
             */
            page_size: number;
            /** @example master,data */
            roles?: string | null;
            /** @example node-1 */
            search?: string;
        };
        /** @description OIDC callback query parameters */
        OidcCallbackQuery: {
            /** @example auth_code_from_provider */
            code: string;
            /** @example random_state_string */
            state: string;
        };
        /** @description OIDC login query parameters */
        OidcLoginQuery: {
            /** @example /clusters */
            redirect_to?: string | null;
        };
        /** @description Generic paginated response wrapper */
        PaginatedResponse_ClusterInfo: {
            /** @description Items for the current page */
            items: {
                accessible: boolean;
                accessible_reason?: string | null;
                id: string;
                /** @description Metrics source (internal or prometheus) */
                metrics_source: components["schemas"]["MetricsSource"];
                name?: string | null;
                nodes: string[];
            }[];
            /** @description Current page number (1-indexed) */
            page: number;
            /** @description Items per page */
            page_size: number;
            /** @description Total count of all items across all pages */
            total: number;
            /** @description Total number of pages */
            total_pages: number;
        };
        /** @description Generic paginated response wrapper */
        PaginatedResponse_IndexInfoResponse: {
            /** @description Items for the current page */
            items: {
                /** Format: int64 */
                docsCount: number;
                health: string;
                name: string;
                /** Format: int32 */
                primaryShards: number;
                /** Format: int32 */
                replicaShards: number;
                status: string;
                /** Format: int64 */
                storeSize: number;
                uuid?: string | null;
            }[];
            /** @description Current page number (1-indexed) */
            page: number;
            /** @description Items per page */
            page_size: number;
            /** @description Total count of all items across all pages */
            total: number;
            /** @description Total number of pages */
            total_pages: number;
        };
        /** @description Generic paginated response wrapper */
        PaginatedResponse_NodeInfoResponse: {
            /** @description Items for the current page */
            items: {
                /** Format: int32 */
                cpuPercent?: number | null;
                /** Format: int64 */
                diskTotal: number;
                /** Format: int64 */
                diskUsed: number;
                /** Format: int64 */
                heapMax: number;
                /** Format: int32 */
                heapPercent: number;
                /** Format: int64 */
                heapUsed: number;
                /** @example node-1 */
                id: string;
                ip?: string | null;
                isMaster: boolean;
                isMasterEligible: boolean;
                loadAverage?: number[] | null;
                name: string;
                roles: string[];
                tags?: string[] | null;
                uptime?: string | null;
                /** Format: int64 */
                uptimeMillis?: number | null;
                version?: string | null;
            }[];
            /** @description Current page number (1-indexed) */
            page: number;
            /** @description Items per page */
            page_size: number;
            /** @description Total count of all items across all pages */
            total: number;
            /** @description Total number of pages */
            total_pages: number;
        };
        /** @description Combined paginated shards response including authoritative node metadata */
        PaginatedShardsWithNodes: {
            items: components["schemas"]["ShardInfoResponse"][];
            nodes: components["schemas"]["NodeInfoResponse"][];
            page: number;
            page_size: number;
            total: number;
            total_pages: number;
        };
        PrometheusValidationRequest: {
            /** @description Optional job name for metric filtering */
            job_name?: string | null;
            /** @description Optional labels for metric filtering */
            labels?: {
                [key: string]: string;
            } | null;
            /**
             * @description Prometheus endpoint URL
             * @example http://prometheus:9090
             */
            url: string;
        };
        /** @description Response for Prometheus validation */
        PrometheusValidationResponse: {
            /** @example Prometheus endpoint is reachable */
            message: string;
            /** @example true */
            reachable: boolean;
            /** @example success */
            status: string;
        };
        /** @description Raw metric data with labels for flexible frontend rendering */
        RawMetrics: {
            /** @description CPU usage points with labels (e.g., node=node-1, node=node-2) */
            cpu?: components["schemas"]["LabeledMetricPoint"][] | null;
            /** @description Memory usage points with labels (e.g., area=heap, area=non-heap) */
            memory?: components["schemas"]["LabeledMetricPoint"][] | null;
        };
        /** @description Readiness check response with dependency status */
        ReadinessResponse: {
            dependencies?: null | components["schemas"]["DependenciesStatus"];
            /** @example Server is ready to accept requests */
            message: string;
            /** @example ready */
            status: string;
        };
        /**
         * @description Request body for shard relocation
         *
         *     # Requirements
         *
         *     Validates: Requirements 6.1, 6.2
         */
        RelocateShardRequest: {
            /**
             * @description Source node ID
             * @example node-1
             */
            from_node: string;
            /**
             * @description Index name
             * @example my-index
             */
            index: string;
            /**
             * Format: int32
             * @description Shard number
             * @example 0
             */
            shard: number;
            /**
             * @description Destination node ID
             * @example node-2
             */
            to_node: string;
        };
        SankeyDataResponse: {
            links: components["schemas"]["SankeyLinkResponse"][];
            meta: components["schemas"]["SankeyMetaResponse"];
            nodes: components["schemas"]["SankeyNodeResponse"][];
        };
        SankeyLinkResponse: {
            /** Format: int32 */
            primaryShards: number;
            /** Format: int32 */
            replicaShards: number;
            source: string;
            target: string;
            /** Format: int32 */
            totalShards: number;
        };
        SankeyMetaResponse: {
            displayedIndices: number;
            totalIndices: number;
            totalLinks: number;
            totalNodes: number;
            truncated: boolean;
        };
        SankeyNodeResponse: {
            id: string;
            kind: string;
            /** Format: int32 */
            primaryShards: number;
            /** Format: int32 */
            replicaShards: number;
            /** Format: int64 */
            storeBytes: number;
            /** Format: int32 */
            totalShards: number;
        };
        /** @description Search statistics */
        SearchStats: {
            /** Format: int64 */
            fetchTimeInMillis: number;
            /** Format: int64 */
            fetchTotal: number;
            /** Format: int32 */
            queryCurrent: number;
            /** Format: int64 */
            queryTimeInMillis: number;
            /** Format: int64 */
            queryTotal: number;
        };
        /** @description Individual shard information */
        ShardInfo: {
            /**
             * Format: int64
             * @description Document count - always present, 0 if unavailable
             */
            docs: number;
            index: string;
            primary: boolean;
            /** Format: int32 */
            shard: number;
            state: string;
            /**
             * Format: int64
             * @description Store size in bytes - always present, 0 if unavailable
             */
            store: number;
        };
        /**
         * @description Shard info response for frontend
         *
         *     # Requirements
         *
         *     Validates: Requirements 9.1, 9.2, 9.3
         */
        ShardInfoResponse: {
            /**
             * Format: int64
             * @description Document count - always present, 0 if unavailable (Requirement 9.3)
             */
            docs: number;
            index: string;
            node?: string | null;
            primary: boolean;
            /** Format: int32 */
            shard: number;
            state: string;
            /**
             * Format: int64
             * @description Store size in bytes - always present, 0 if unavailable (Requirement 9.3)
             */
            store: number;
        };
        /** @description Shard statistics for a node */
        ShardStats: {
            list: components["schemas"]["ShardInfo"][];
            /** Format: int32 */
            primary: number;
            /** Format: int32 */
            replica: number;
            /** Format: int32 */
            total: number;
        };
        /**
         * @description Get shards information for a cluster with pagination and filtering
         *
         *     # Requirements
         *
         *     Validates: Requirements 4.8
         */
        ShardsQueryParams: {
            /** @example true */
            hide_special?: boolean;
            /** @example logs- */
            index?: string;
            /** @example node-1 */
            node?: string;
            /**
             * Format: int32
             * @default 1
             * @example 1
             */
            page: number;
            /**
             * Format: int32
             * @default 10
             * @example 10
             */
            page_size: number;
            /** @example logs */
            search?: string;
            /** @example true */
            show_primaries?: boolean;
            /** @example true */
            show_replicas?: boolean;
            /** @example STARTED,UNASSIGNED */
            state?: string;
        };
        /**
         * @description Detailed task information from Elasticsearch Tasks Get API
         *
         *     Includes full task details and raw JSON response
         */
        TaskDetails: components["schemas"]["TaskInfo"] & {
            /** @description Raw Elasticsearch response for full details */
            raw?: unknown;
        };
        /** @description Response from get task details endpoint */
        TaskDetailsResponse: {
            task: components["schemas"]["TaskDetails"];
        };
        /**
         * @description Task information from Elasticsearch Tasks API
         *
         *     Represents a single active task in the cluster
         */
        TaskInfo: {
            /**
             * @description Task action (e.g., "cluster:monitor/tasks/lists", "indices:data/read/search")
             * @example cluster:monitor/tasks/lists
             */
            action: string;
            /**
             * @description Whether the task can be cancelled
             * @example true
             */
            cancellable: boolean;
            /**
             * @description Whether the task is already cancelled
             * @example false
             */
            cancelled: boolean;
            /**
             * Format: int64
             * @description Unique task ID within the node
             * @example 123
             */
            id: number;
            /**
             * @description Node ID where the task is running
             * @example node1
             */
            node: string;
            /** @description Parent task ID if this is a subtask */
            parent_task_id?: string | null;
            /**
             * Format: int64
             * @description Running time in milliseconds (calculated client-side if needed)
             */
            running_time_millis?: number | null;
            /**
             * Format: int64
             * @description Start time in milliseconds since epoch
             * @example 1704067200
             */
            start_time_in_millis: number;
            /**
             * @description Task type (e.g., "transport", "management", "search")
             * @example transport
             */
            type: string;
        };
        /** @description Response from list tasks endpoint */
        TasksListResponse: {
            tasks: components["schemas"]["TaskInfo"][];
            /**
             * Format: int64
             * @example 1704067200
             */
            timestamp: number;
            unique_actions: string[];
            unique_types: string[];
        };
        /** @description Query parameters for listing tasks */
        TasksQueryParams: {
            /** @description Comma-separated list of task actions to filter */
            action_filter?: string | null;
            /** @description Comma-separated list of task types to filter */
            type_filter?: string | null;
        };
        /** @description Thread pool statistics */
        ThreadPoolStats: {
            /** Format: int32 */
            active: number;
            /** Format: int64 */
            completed: number;
            /** Format: int32 */
            largest: number;
            /** Format: int32 */
            queue: number;
            /** Format: int64 */
            rejected: number;
            /** Format: int32 */
            threads: number;
        };
        TileBatchRequest: {
            tileRequests: components["schemas"]["TileRequestEntry"][];
        };
        TileBatchResponse: {
            serverVersion: string;
            tiles: components["schemas"]["TilePayload"][];
        };
        TileNodeMeta: {
            /** Format: int64 */
            height: number;
            id: string;
            metrics?: unknown;
            /** @example node-1 */
            name?: string | null;
            summaryCounts?: unknown;
            /** Format: int64 */
            width: number;
            /** Format: int64 */
            x: number;
            /** Format: int64 */
            y: number;
        };
        /**
         * @description TilePayload is the per-tile response sent to clients. It is JSON-valued
         *     in practice (nodes_meta and shards use serde_json::Value) but we derive
         *     ToSchema here so utoipa can include a schema for OpenAPI generation.
         */
        TilePayload: {
            edges?: unknown;
            lod: string;
            /** @description Lightweight nodes metadata (no heavy per-node shard arrays). */
            nodesMeta?: unknown;
            /** @description Optional mapping of nodeId -> shards array. Present for L2 tiles. */
            shards?: unknown;
            unchanged: boolean;
            version: string;
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
        };
        TileRequestEntry: {
            clientVersion?: string | null;
            lod: string;
            /** Format: int32 */
            x: number;
            /** Format: int32 */
            y: number;
        };
        /** @description Time range for metrics queries */
        TimeRange: {
            /**
             * Format: int64
             * @description End timestamp (Unix seconds)
             */
            end: number;
            /**
             * Format: int64
             * @description Start timestamp (Unix seconds)
             */
            start: number;
        };
        /** @description User info response */
        UserInfoResponse: {
            /** @description Cluster IDs the user can access (resolved server-side) */
            accessible_clusters: string[];
            /** @description Authentication method used: "local", "ldap", "oidc", or "open" */
            auth_type: string;
            /** @description User groups/roles */
            groups: string[];
            /** @example admin */
            username: string;
        };
        /** @description Version response */
        VersionResponse: {
            /** @example v1.2.28-5-g1234567 */
            git_info: string;
            /** @example 1.2.28 */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to login page */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfoResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oidc_callback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                state: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect after successful login */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    oidc_login: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                redirect_to: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to OIDC provider */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_auth_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_clusters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                page: number;
                page_size: number;
                search: string;
                health: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ClusterInfo"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_indices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                page: number;
                page_size: number;
                search: string;
                health: string;
                status: string;
                show_special: boolean;
                affected: boolean;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_IndexInfoResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_shard_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                /** @description Index name */
                index_name: string;
                /** @description Shard number */
                shard_num: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shard stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_nodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                page: number;
                page_size: number;
                search: string;
                roles: string | null;
                nodes: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_NodeInfoResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_node_shards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                /** @description Node ID */
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShardInfoResponse"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_node_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                /** @description Node ID */
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetailStatsResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    proxy_request: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                /** @description Elasticsearch API path */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Elasticsearch response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    relocate_shard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelocateShardRequest"];
            };
        };
        responses: {
            /** @description Shard relocation initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_cluster_settings: {
        parameters: {
            query: {
                /** @description Include default settings */
                include_defaults: boolean;
            };
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    update_cluster_settings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterSettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_shards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                page: number;
                page_size: number;
                hide_special: boolean;
                show_primaries: boolean;
                show_replicas: boolean;
                state: string;
                index: string;
                node: string;
                search: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedShardsWithNodes"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_cluster_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterStatsResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    fetch_cluster_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                /**
                 * @description Comma-separated list of task types to filter
                 * @example transport,search
                 */
                type_filter: string | null;
                /**
                 * @description Comma-separated list of task actions to filter
                 * @example cluster:monitor/tasks/lists
                 */
                action_filter: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TasksListResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_task_details: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                /** @description Task ID (format: node_id:task_number) */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailsResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    cancel_cluster_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                /** @description Task ID (format: node_id:task_number) */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelTaskResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_sankey: {
        parameters: {
            query?: {
                /** @description Max indices to show (0 = nothing, default 10) */
                top_indices?: number;
                /** @description Include unassigned shards node (default true) */
                include_unassigned?: boolean;
                /** @description Comma-separated node roles filter */
                roles?: string;
                /** @description Comma-separated shard states filter */
                states?: string;
            };
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SankeyDataResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    post_tiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TileBatchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TileBatchResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    validate_prometheus_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrometheusValidationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrometheusValidationResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_cluster_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                /** @description Start timestamp (Unix seconds). If not provided, defaults to 24 hours ago */
                start: number | null;
                /** @description End timestamp (Unix seconds). If not provided, defaults to now */
                end: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterMetricsHistoryResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_cluster_metrics_history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                /** @description Start timestamp (Unix seconds). If not provided, defaults to 24 hours ago */
                start: number | null;
                /** @description End timestamp (Unix seconds). If not provided, defaults to now */
                end: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster metrics history for heatmap */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    get_node_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID */
                cluster_id: string;
                /** @description Node ID */
                node_id: string;
                /** @description Start timestamp (Unix seconds). If not provided, defaults to 24 hours ago */
                start: number | null;
                /** @description End timestamp (Unix seconds). If not provided, defaults to now */
                end: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeMetricsHistoryResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterErrorResponse"];
                };
            };
        };
    };
    readiness_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Server is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
